version: '2'
services:
  web:
    build: ./docker-files/web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    links:
      - php
  php:
    build: ./docker-files/php
    ports:
      - "9000"
    volumes:
      - .:/var/www
